#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/
#    username: admin
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate.ddl-auto: update