server:
  port: 3000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:teste
    username: admin
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        #      estrategia de geração automatica do schema do banco de dados, não recomendado para ambiente produtivo
        #      ddl-auto: create
        format_sql: true
        show_sql: true